import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';

// This script is ran when the root package is updated (which happens before child packages)
const packageJsonUrl = resolve(process.cwd(), 'package.json');
const packageJson = JSON.parse(readFileSync(packageJsonUrl));

const content = `
// this is an autogenerated file, see scripts/version-update.js
export const VERSION = '${packageJson.version}';
`;

const fileUrl = resolve(process.cwd(), 'src', 'version.ts');
writeFileSync(fileUrl, content);
